In [128]:
import pandas as pd

In [129]:
dataset = pd.read_csv('Hackathondata.csv')

In [130]:
dataset

DRG Definition  \
0       207 - RESPIRATORY SYSTEM DIAGNOSIS W VENTILATO...   
1       207 - RESPIRATORY SYSTEM DIAGNOSIS W VENTILATO...   
2        870 - SEPTICEMIA OR SEVERE SEPSIS W MV 96+ HOURS   
3        870 - SEPTICEMIA OR SEVERE SEPSIS W MV 96+ HOURS   
4        870 - SEPTICEMIA OR SEVERE SEPSIS W MV 96+ HOURS   
...                                                   ...   
163060                     948 - SIGNS & SYMPTOMS W/O MCC   
163061                                   313 - CHEST PAIN   
163062  310 - CARDIAC ARRHYTHMIA & CONDUCTION DISORDER...   
163063   918 - POISONING & TOXIC EFFECTS OF DRUGS W/O MCC   
163064                                   313 - CHEST PAIN   

       Hospital Referral Region Description  Average Covered Charges  
0                     CA - San Mateo County                929118.90  
1                       CA - Alameda County                918023.18  
2                     CA - San Mateo County                637377.71  
3                          CA - Los Angeles                375878.20  
4                        CA - San Francisco                447714.88  
...                                     ...                      ...  
163060                          WY - Casper                 12021.42  
163061                          WY - Casper                  8548.52  
163062                          WY - Casper                 13347.00  
163063                          WY - Casper                 16805.27  
163064                          WY - Casper                 15558.64  

[163065 rows x 3 columns]

In [131]:
dataset['Average Covered Charges'] = dataset['Average Covered Charges'].astype(float)

In [136]:
from sklearn.tree import DecisionTreeRegressor
dec_tree_reg = DecisionTreeRegressor(random_state=0)
dec_tree_reg.fit(X,y)

DecisionTreeRegressor(random_state=0)

In [137]:
y_pred = dec_tree_reg.predict(X)


In [138]:
from sklearn.metrics import mean_squared_error,mean_absolute_error
import numpy as np
error = np.sqrt(mean_squared_error(y,y_pred))

In [139]:
error

15278.102545599171

In [140]:
X

DRG Definition  Hospital Referral Region Description
0                   21                                    34
1                   21                                    16
2                   92                                    34
3                   92                                    21
4                   92                                    31
...                ...                                   ...
163060              99                                   305
163061              49                                   305
163062              47                                   305
163063              98                                   305
163064              49                                   305

[163065 rows x 2 columns]

In [132]:
from sklearn.preprocessing import LabelEncoder
le_drg = LabelEncoder()
dataset['DRG Definition'] = le_drg.fit_transform(dataset['DRG Definition'])
dataset['DRG Definition'].unique()

array([ 21,  92,  91,  52, 100,  53,  36,  70,  30,  66,  50,  67,  26,
        22,  93,  24,  23,  55,  10,   2,  31,  68,  87,  38,  16,  71,
        33,  97,  12,  77,  82,  80,  69,  29,  37,  25,  89,  11,  13,
         3,  27,  95,   1,  17,  28,  63,  32,  90,  45,  85,  72,  60,
        79,  96,  54,  19,  39,  94,  34,  62,  56,  86,  51,  83,  14,
        65,   9,  58,  88,  81,   4,  40,  78,   6,  64,  41,  46,  98,
         0,  61,  75,  73,  99,  76,  15,   7,  57,  48,  18,  59,  35,
        42,  74,   5,  49,  44,  43,  47,  84,   8,  20])

In [133]:
from sklearn.preprocessing import LabelEncoder
le_hosp = LabelEncoder()
dataset['Hospital Referral Region Description'] = le_hosp.fit_transform(dataset['Hospital Referral Region Description'])
dataset['Hospital Referral Region Description'].unique()

array([ 34,  16,  21,  31,  29,  28,  32,  19,  27,  39,  30,  22,  23,
        37,  18,  36,  24,  17,  38,  35,  20,  26,  25,  33,  13, 222,
       264, 260, 270, 266, 267, 263, 268, 262, 256, 255, 271, 275, 261,
        11, 259, 274, 258, 272, 254, 273, 257, 269, 265, 125, 206, 203,
       199, 201, 205, 197, 204, 200, 287, 188, 193, 202, 189, 198,  49,
       228, 235,  60,  69,  54,  56,  58,  59,  62,  52,  67,  55,  68,
        65,  66,  63,  57,  53,  61,  64,   2, 229, 232, 227, 233, 234,
       225, 238, 237, 236, 231, 226, 230, 216, 304,  91,  96,  92,  97,
        90,  98,  93, 100,  89,  99,  94, 299,  95,  88, 160, 116,  79,
       101, 215, 209, 211, 210, 212, 207, 214, 213, 208, 102, 135, 138,
       137, 145, 141, 146, 139, 140, 147, 136, 149, 142, 144, 143, 148,
       295, 172, 178, 174, 171, 176, 177, 170, 283, 249, 173, 175,  71,
        72,  74,  73,  70,  76,  75, 247, 127, 129, 128, 239, 191, 190,
       187, 192,  51, 284, 280, 279, 282, 285, 250, 286, 281, 10

In [134]:
X = dataset.drop("Average Covered Charges",axis=1)
y = dataset["Average Covered Charges"]


In [142]:
X

array([['312 - SYNCOPE & COLLAPSE', 'CA - Los Angeles']], dtype='<U24')

In [146]:
X = np.array([["312 - SYNCOPE & COLLAPSE","CA - Los Angeles"]])

In [147]:
X[:,0]= le_drg.transform(X[:,0])
X[:,1]= le_hosp.transform(X[:,1])
X

array([['48', '21']], dtype='<U24')

In [148]:
y_pred = dec_tree_reg.predict(X)
y_pred

c:\users\ashray gattani\appdata\local\programs\python\python39\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(


array([34168.48551724])

In [149]:
import pickle

In [150]:
data = {"model":dec_tree_reg,"le_DRG":le_drg,"le_hosp":le_hosp}
with open('Saved_steps.pkl','wb') as file:
    pickle.dump(data,file)
    

In [151]:
with open('Saved_steps.pkl','rb') as file:
    data = pickle.load(file)
regressor_loaded = data["model"]
le_drg = data["le_DRG"]
le_hosp = data["le_hosp"]

In [152]:
y_ped = regressor_loaded.predict(X)
y_pred

c:\users\ashray gattani\appdata\local\programs\python\python39\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(


array([34168.48551724])